---
- hosts: aio
  become: no
  gather_facts: no
  pre_tasks:
    - name: Wait for SSH
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        timeout: 320
        state: started
      delegate_to: localhost

- hosts: aio
  become: yes
  roles:
    - role: openstack-deploy-host
    - role: openstack-target-host

- hosts: aio
  become: yes
  roles:
  tasks:
    - name: Ensure the checkout dir exists
      file:
        path: "{{ checkout_dir }}"
        state: directory

    - name: Clone the specified version of openstack-ansible
      git:
        repo: https://github.com/openstack/openstack-ansible.git
        version: "{{ ansible_openstack_tag }}"
        dest: "{{ checkout_dir }}"
        accept_hostkey: yes
#   - name: bootstrap-ansible.sh
#     shell: "{{ checkout_dir }}/scripts/bootstrap-ansible.sh"
#     args:
#       chdir: "{{ checkout_dir }}"
#   - name: bootstrap-aio.sh
#     shell: "{{ checkout_dir }}/scripts/bootstrap-aio.sh"
#     args:
#       chdir: "{{ checkout_dir }}"
#   - name: run-playbooks.sh
#     shell: "{{ checkout_dir }}/scripts/run-playbooks.sh"
#     args:
#       chdir: "{{ checkout_dir }}"
